#ifndef __CONST_MENU_CHOSE_SILENCE_RESET_TEST__
#define __CONST_MENU_CHOSE_SILENCE_RESET_TEST__

#define EKRAN_RANGUVANNJA_SILENCE               (EKRAN_VIEW_TIMEOUT_RS485 + 1)
#define EKRAN_RANGUVANNJA_RESET                 (EKRAN_RANGUVANNJA_SILENCE + 1)
#define EKRAN_RANGUVANNJA_TEST                  (EKRAN_RANGUVANNJA_RESET + 1)

#define MAX_ROW_RANGUVANNJA_SILENCE             NUMBER_TOTAL_SIGNAL_FOR_RANG
#define MAX_ROW_RANGUVANNJA_RESET               NUMBER_TOTAL_SIGNAL_FOR_RANG



#endif
