#ifndef __CONST_MENU_MEASURMENT__
#define __CONST_MENU_MEASURMENT__

#define EKRAN_MEASURMENT_CURRENT        (EKRAN_COFIGURATION + 1)

#define MAX_ROW_FOR_MEASURMENT_ANALOG_INPUT          NUMBER_ANALOG_CANALES


#endif
